### ISSUE TITLE
An instance of ParadoxAccountSaveData singleton does not exists

### ISSUE THREAD

**Issue by KrristophC** [pj1234678/MagickaFix#10]
I got this message every time moments after loading into the game.

```
System.NullReferenceException: An instance of ParadoxAccountSaveData singleton does not exists.
   at Magicka.Misc.ScopedSingleton`1.get_Instance()
   at Magicka.WebTools.Paradox.AccountSequence.GameStartupSequence.AccountLoginWithSteamTicketFailedCallback(String iReason)
   at Magicka.WebTools.Paradox.ParadoxServices.PendingAsyncOperation`1.EndIfComplete()
   at Magicka.WebTools.Paradox.ParadoxServices.Update()
   at Magicka.Game.Update(Single iDeltaTime)
   at Magicka.Game.ThreadedUpdate()
   at Magicka.Misc.TrackedThread.StartThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by pj1234678** [comment]
Hey my friend, are you modifying the steam_api.dll?

That error is when it can't get a valid steam license.

**Comment by KrristophC** [comment]
I just put your files straight into steam download, no other modifications. I see you updated few files, I'll  check up on that now.

**Comment by pj1234678** [comment]
Thanks.

Could you provide a log?

I will try to reproduce this later tonight.

**Comment by pj1234678** [comment]
Oops you already provided one.

My bad.

I'll report back later today
