### ISSUE TITLE
Out of memory crash after acquiring Rain Magick

### ISSUE THREAD

**Issue by pitprok** [pj1234678/MagickaFix#22]
I am using the newest version of MagickaFix

Version: 1.10.4.2	Thread: LoaderThread

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Microsoft.Xna.Framework.Helpers.GetExceptionFromResult(UInt32 result)
   at Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(GraphicsDevice graphicsDevice, Byte[] effectCode, CompilerOptions options, EffectPool pool)
   at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode, CompilerOptions options, EffectPool pool)
   at PolygonHead.Effects.RenderDeferredEffect..ctor(GraphicsDevice iDevice, EffectPool iPool)
   at PolygonHead.Effects.RenderDeferredEffect.Read(ContentReader iInput)
   at PolygonHead.Pipeline.RenderDeferredEffectReader.Read(ContentReader input, RenderDeferredEffect existingInstance)
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources(Int32 sharedResourceCount)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]()
   at Magicka.GameLogic.Entities.Items.Item.Read(ContentReader iInput)
   at Magicka.ContentReaders.ItemReader.Read(ContentReader iInput, Item existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]()
   at Magicka.GameLogic.Entities.Items.Attachment..ctor(ContentReader iInput, SkinnedModelBoneCollection iSkeleton)
   at Magicka.GameLogic.Entities.CharacterTemplate.Read(ContentReader iInput)
   at Magicka.ContentReaders.CharacterTemplateReader.Read(ContentReader input, CharacterTemplate existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Magicka.SharedContentManager.Load[T](String assetName)
   at Magicka.Levels.Triggers.Actions.Spawn.Initialize()
   at Magicka.Levels.Triggers.Trigger.Initialize()
   at Magicka.Levels.GameScene.Initialize(SpawnPoint iSpawnPoint, Boolean iClearAudio, Action`1 reportbackAction)
   at Magicka.Levels.Level.ChangeScene()
   at Magicka.Game.LoaderFunction()
   at Magicka.Misc.TrackedThread.StartThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[LoaderThread]0x02fc Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Helpers.GetExceptionFromResult
[LoaderThread]0x00ca Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode
[LoaderThread]0x002a Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Graphics.Effect..ctor
[LoaderThread]0x0000 PolygonHead.dll->PolygonHead.Effects.RenderDeferredEffect..ctor
[LoaderThread]0x002b PolygonHead.dll->PolygonHead.Effects.RenderDeferredEffect.Read
[LoaderThread]0x0000 PolygonHead.dll->PolygonHead.Pipeline.RenderDeferredEffectReader.Read
[LoaderThread]0x0046 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read
[LoaderThread]0x0030 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x001c Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources
[LoaderThread]0x000e Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0021 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference
[LoaderThread]0x0753 Magicka.exe->Magicka.GameLogic.Entities.Items.Item.Read
[LoaderThread]0x0000 Magicka.exe->Magicka.ContentReaders.ItemReader.Read
[LoaderThread]0x0023 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x0000 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObject
[LoaderThread]0x0007 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0021 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference
[LoaderThread]0x00d7 Magicka.exe->Magicka.GameLogic.Entities.Items.Attachment..ctor
[LoaderThread]0x0861 Magicka.exe->Magicka.GameLogic.Entities.CharacterTemplate.Read
[LoaderThread]0x0000 Magicka.exe->Magicka.ContentReaders.CharacterTemplateReader.Read
[LoaderThread]0x0023 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x0000 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObject
[LoaderThread]0x0007 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0008 Magicka.exe->Magicka.SharedContentManager.Load
[LoaderThread]0x0000 Magicka.exe->Magicka.Levels.Triggers.Actions.Spawn.Initialize
[LoaderThread]0x004d Magicka.exe->Magicka.Levels.Triggers.Trigger.Initialize
[LoaderThread]0x0051 Magicka.exe->Magicka.Levels.GameScene.Initialize
[LoaderThread]0x00f5 Magicka.exe->Magicka.Levels.Level.ChangeScene
[LoaderThread]0x003a Magicka.exe->Magicka.Game.LoaderFunction
[LoaderThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
[LoaderThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
[LoaderThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
[LoaderThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart

[LogicThread]0x0080 Magicka.exe->Magicka.Game.ThreadedUpdate
[LogicThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
[LogicThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
[LogicThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
[LogicThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart

**Comment by pj1234678** [comment]
is it always when you get the rain magick?
