### ISSUE TITLE
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by hnrq** [pj1234678/MagickaFix#4]
Magicka keeps crashing with OOM Exception being thrown.

Specs:
Windows 11
16GB RAM
AMD RX6600M
Ryzen 7

<details><summary>Error log</summary>
<pre>
Version: 1.10.4.2	Thread: LoaderThread

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Xna.Framework.Content.DecompressStream..ctor(Stream baseStream, Int32 compressedTodo, Int32 decompressedTodo)
   at Microsoft.Xna.Framework.Content.ContentReader.PrepareStream(Stream input, String assetName)
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]()
   at PolygonHead.Effects.RenderDeferredEffect.Read(ContentReader iInput)
   at PolygonHead.Pipeline.RenderDeferredEffectReader.Read(ContentReader input, RenderDeferredEffect existingInstance)
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources(Int32 sharedResourceCount)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]()
   at Magicka.GameLogic.Entities.Items.Item.Read(ContentReader iInput)
   at Magicka.ContentReaders.ItemReader.Read(ContentReader iInput, Item existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference[T]()
   at Magicka.GameLogic.Entities.Items.Attachment..ctor(ContentReader iInput, SkinnedModelBoneCollection iSkeleton)
   at Magicka.GameLogic.Entities.CharacterTemplate.Read(ContentReader iInput)
   at Magicka.ContentReaders.CharacterTemplateReader.Read(ContentReader input, CharacterTemplate existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InvokeReader[T](ContentTypeReader reader, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal[T](Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Magicka.SharedContentManager.CommonContentManager.Load[T](String assetName)
   at Magicka.SharedContentManager.Load[T](String assetName)
   at Magicka.Levels.Triggers.Actions.Spawn.Initialize()
   at Magicka.Levels.Triggers.Trigger.Initialize()
   at Magicka.Levels.GameScene.Initialize(SpawnPoint iSpawnPoint, Boolean iClearAudio, Action`1 reportbackAction)
   at Magicka.Levels.Level.ChangeScene()
   at Magicka.Game.LoaderFunction()
   at Magicka.Misc.TrackedThread.StartThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[LoaderThread]0x002b Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.DecompressStream..ctor
[LoaderThread]0x00d7 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.PrepareStream
[LoaderThread]0x002f Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0021 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference
[LoaderThread]0x00c7 PolygonHead.dll->PolygonHead.Effects.RenderDeferredEffect.Read
[LoaderThread]0x0000 PolygonHead.dll->PolygonHead.Pipeline.RenderDeferredEffectReader.Read
[LoaderThread]0x0046 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read
[LoaderThread]0x0030 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x001c Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources
[LoaderThread]0x000e Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0021 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference
[LoaderThread]0x0753 Magicka.exe->Magicka.GameLogic.Entities.Items.Item.Read
[LoaderThread]0x0000 Magicka.exe->Magicka.ContentReaders.ItemReader.Read
[LoaderThread]0x0023 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x0000 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObject
[LoaderThread]0x0007 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0021 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference
[LoaderThread]0x00d7 Magicka.exe->Magicka.GameLogic.Entities.Items.Attachment..ctor
[LoaderThread]0x0861 Magicka.exe->Magicka.GameLogic.Entities.CharacterTemplate.Read
[LoaderThread]0x0000 Magicka.exe->Magicka.ContentReaders.CharacterTemplateReader.Read
[LoaderThread]0x0023 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.InvokeReader
[LoaderThread]0x0040 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObjectInternal
[LoaderThread]0x0000 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadObject
[LoaderThread]0x0007 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentReader.ReadAsset
[LoaderThread]0x0039 Microsoft.Xna.Framework.dll->Microsoft.Xna.Framework.Content.ContentManager.ReadAsset
[LoaderThread]0x002b Magicka.exe->Magicka.SharedContentManager+CommonContentManager.Load
[LoaderThread]0x0008 Magicka.exe->Magicka.SharedContentManager.Load
[LoaderThread]0x0000 Magicka.exe->Magicka.Levels.Triggers.Actions.Spawn.Initialize
[LoaderThread]0x004d Magicka.exe->Magicka.Levels.Triggers.Trigger.Initialize
[LoaderThread]0x0051 Magicka.exe->Magicka.Levels.GameScene.Initialize
[LoaderThread]0x00f5 Magicka.exe->Magicka.Levels.Level.ChangeScene
[LoaderThread]0x003a Magicka.exe->Magicka.Game.LoaderFunction
[LoaderThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
[LoaderThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
[LoaderThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
[LoaderThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart

[LogicThread]0x0080 Magicka.exe->Magicka.Game.ThreadedUpdate
[LogicThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
[LogicThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
[LogicThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
[LogicThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart
</pre>
</details>

**Comment by pj1234678** [comment]
Thank you for this.
In the next few weeks my team will be testing random computers to try to eliminate this issue.
It is very cat and mouse and may seem to do with AMD from all the reports we have received.

**Comment by ObsceneDream** [comment]
No idea how to do this so it may be wrong. Same issues though.

Specs
Windows 10 
16GB
Nvidia 2070
i7 9700k

> Version: 1.10.4.2	Thread: LoaderThread
> 
> 
> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at Magicka.GameLogic.Entities.Avatar..ctor(PlayState iPlayState)
>    at Magicka.GameLogic.Entities.Avatar.InitializeCache(PlayState iPlayState)
>    at Magicka.GameLogic.GameStates.PlayState.Initialize()
>    at Magicka.Game.LoaderFunction()
>    at Magicka.Misc.TrackedThread.StartThread()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> 
> 
> [LoaderThread]0x00c6 Magicka.exe->Magicka.GameLogic.Entities.Avatar..ctor
> [LoaderThread]0x0025 Magicka.exe->Magicka.GameLogic.Entities.Avatar.InitializeCache
> [LoaderThread]0x0610 Magicka.exe->Magicka.GameLogic.GameStates.PlayState.Initialize
> [LoaderThread]0x003a Magicka.exe->Magicka.Game.LoaderFunction
> [LoaderThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
> [LoaderThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
> [LoaderThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
> [LoaderThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart
> 
> 
> [LogicThread]0x0080 Magicka.exe->Magicka.Game.ThreadedUpdate
> [LogicThread]0x0000 Magicka.exe->Magicka.Misc.TrackedThread.StartThread
> [LogicThread]0x003b CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart_Context
> [LogicThread]0x005f CommonLanguageRuntimeLibrary->System.Threading.ExecutionContext.Run
> [LogicThread]0x002a CommonLanguageRuntimeLibrary->System.Threading.ThreadHelper.ThreadStart

**Comment by MADCATXXX** [comment]
For me the game crashes almost instantly if game resolution is set to 4K and you host the multiplayer game.
My config:
I9-13900k, 64Gb DDR5-5600, Nvidia RTX4090, Desktop resolution 3840*2160 pixels.

Game almost instantly goes up to 1.3 GB Ram usage and crashes.
XNA Dot.net framework 32 bit apps are limited to 1.5 GB heap memory limit and it's reached almost instantly.

[https://stackoverflow.com/questions/659119/how-can-i-increase-the-heap-size-net](https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F659119%2Fhow-can-i-increase-the-heap-size-net)
[https://stackoverflow.com/questions/11702830/can-an-xna-game-use-more-than-1-5gb-of-ram-and-not-crash](https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F11702830%2Fcan-an-xna-game-use-more-than-1-5gb-of-ram-and-not-crash)
[https://stackoverflow.com/questions/39111650/xna-fires-outofmemoryexception-on-1-3gb](https://steamcommunity.com/linkfilter/?u=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F39111650%2Fxna-fires-outofmemoryexception-on-1-3gb)

**Comment by pj1234678** [comment]
Thank you for the report.
I finally found a solution, Since the binary runs in 32 bit mode it can't use more than ~1.3GB of ram.
In version 1.5 I address this by adding the LARGEADDRESSAWARE flag to the binary header.

I will mark this closed when 1.5 drops in a few hours.

MADCATXXX was correct and has aided me in this solution.

**Comment by pj1234678** [comment]
The new version dropped Addressing a lot of these concerns
Please update and if you have the same issue open a new one.
